### ISSUE TITLE
Broken markdown-to-html rendering

### ISSUE THREAD

**Issue by jwarner112** [ChristianSiegert/panoptikos#35]
Hello,

Recently, posts in Panoptikos stopped properly rendering and now the raw markdown is shown. While still navigable, this has been a detrimental blow to the user experience for text posts. Granted that's not the primary use case of the app, it was still a fantastic platform for reading until the breakage.

I'm assuming Reddit changed the API to stop pre-rendering HTML or something, because the rest of the app still works flawlessly.

Thanks for making this, by the way, I struggled with not wanting to install an app and not using Reddit's mobile site for years before I discovered this. 🍻

**Comment by ChristianSiegert** [comment]
@jwarner112 Panoptikos is now [popular.pics](https://www.popular.pics). Are you referring to popular.pics or is there some old version of Panoptikos floating around the Internet?

Good news, self-texts and comments are now formatted properly (on popular.pics).

**Comment by jwarner112** [comment]
Hey @ChristianSiegert, thanks for the response. I was referring to popular.pics, which I'd assumed was just the live version of this repo. Is that not the case?

I noticed the parsing got fixed a few weeks back and have really appreciated!
